# Generated by Django 5.0.6 on 2026-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('name_uk', models.CharField(max_length=120, null=True, verbose_name="Ім'я")),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name="Ім'я")),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фото')),
                ('english_level', models.CharField(max_length=40, verbose_name='Рівень англійської')),
                ('english_level_uk', models.CharField(max_length=40, null=True, verbose_name='Рівень англійської')),
                ('english_level_en', models.CharField(max_length=40, null=True, verbose_name='Рівень англійської')),
                ('experience', models.CharField(blank=True, max_length=200, verbose_name='Досвід')),
                ('experience_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Досвід')),
                ('experience_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Досвід')),
                ('bio', models.TextField(blank=True, verbose_name='Опис')),
                ('bio_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
                'ordering': ('order', 'id'),
            },
        ),
    ]
