# Generated by Django 5.0.6 on 2026-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=120, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Назва')),
                ('lessons_count', models.PositiveIntegerField(default=1, verbose_name='Кількість занять')),
                ('price_per_lesson', models.PositiveIntegerField(default=0, verbose_name='Ціна за урок (грн)')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Загальна вартість (грн)')),
                ('is_speaking_club', models.BooleanField(default=False, verbose_name='Speaking Club')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Переваги (список)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примітка')),
                ('note_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примітка')),
                ('note_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примітка')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Виділити (популярний)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ('order', 'id'),
            },
        ),
    ]
