# Generated by Django 5.0.6 on 2026-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок hero')),
                ('hero_title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок hero')),
                ('hero_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок hero')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок hero')),
                ('hero_subtitle_uk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Підзаголовок hero')),
                ('hero_subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Підзаголовок hero')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('base_lesson_price', models.PositiveIntegerField(default=400, verbose_name='Базова ціна 1 уроку (грн)')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
