# Generated by Django 5.0.6 on 2026-06-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('englishtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('source', models.CharField(choices=[('test', 'Через тест'), ('form', 'Через форму')], default='form', max_length=10, verbose_name='Джерело')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Відповіді тесту')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='englishtest.level', verbose_name='Рівень (з тесту)')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='englishtest.testsubmission', verbose_name='Проходження тесту')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
    ]
