# Generated by Django 5.0.6 on 2026-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='channel',
            field=models.CharField(choices=[('site', 'Сайт'), ('bot', 'Telegram-бот')], default='site', max_length=10, verbose_name='Канал'),
        ),
    ]
