# Generated by Django 5.0.6 on 2026-06-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код (A1..C2)')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=120, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('min_score', models.PositiveIntegerField(default=0, verbose_name='Мін. балів')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Макс. балів')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Рівень',
                'verbose_name_plural': 'Рівні (CEFR)',
                'ordering': ('order', 'min_score'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Питання')),
                ('text_uk', models.TextField(null=True, verbose_name='Питання')),
                ('text_en', models.TextField(null=True, verbose_name='Питання')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Балів за правильну відповідь')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання тесту',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст відповіді')),
                ('text_uk', models.CharField(max_length=300, null=True, verbose_name='Текст відповіді')),
                ('text_en', models.CharField(max_length=300, null=True, verbose_name='Текст відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='englishtest.question', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набрано балів')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимум балів')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Відповіді')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='englishtest.level', verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Проходження тесту',
                'verbose_name_plural': 'Проходження тесту',
                'ordering': ('-created_at',),
            },
        ),
    ]
